export const MenuItems = [
    {
        title:"Home",
        url:"/",
        cName:"nav_links",
        icon:"fa-light fa-house"
    },
    {
        title:"Penal",
        url:"/",
        cName:"nav_links",
        icon:"/"
    },
    {
        title:"Divorce",
        url:"/",
        cName:"nav_links",
        icon:"/"
    },
    {
        title:"Civil",
        url:"/",
        cName:"nav_links",
        icon:"/"
    },
    {
        title:"Internacional",
        url:"/",
        cName:"nav_links",
        icon:"/"
    },
    {
        title:"Mercantil",
        url:"/",
        cName:"nav_links",
        icon:"/"
    },
    {
        title:"Despacho",
        url:"/",
        cName:"nav_links",
        icon:"/"
    },
    {
        title:"Contacto",
        url:"/",
        cName:"nav_links",
        icon:"/"
    }
]